git:
  depth: false
language: rust
rust:
  - nightly
before_script:
  - rustup component add clippy
  - cd raytracer
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
