git:
  depth: false
before_script: cd raytracer
language: rust
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
