[package]
name = "raytracer"
version = "0.1.0"
authors = ["Jordan Osborn <jordanosborn0@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Raytracer"

[profile.dev]
debug = true
opt-level = 1

[dependencies]
rand = "0.6.4"
rayon = "1.0.3"
indicatif = "0.11.0"
image = "0.20.1"